import type { ChapterPrereadingResponse } from '@/api/generated/model';
import { AIIcon } from '@/theme/Icons';
import { Box, Button, CircularProgress, Typography } from '@mui/material';

interface PrereadingContentProps {
  content?: ChapterPrereadingResponse | null;
  onGenerate: () => void;
  isGenerating: boolean;
}

export const PrereadingContent = ({
  content,
  onGenerate,
  isGenerating,
}: PrereadingContentProps) => {
  if (isGenerating) {
    return (
      <Box sx={{ p: 2, textAlign: 'center' }}>
        <CircularProgress size={24} />
        <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
          Generating pre-reading overview...
        </Typography>
      </Box>
    );
  }

  if (!content) {
    return (
      <Box sx={{ p: 2 }}>
        <Button variant="outlined" onClick={onGenerate} startIcon={<AIIcon />}>
          Generate Pre-reading Overview
        </Button>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 2, bgcolor: 'background.paper', borderRadius: 1, mb: 2 }}>
      <Typography variant="body1" sx={{ mb: 2 }}>
        {content.summary}
      </Typography>

      <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 600 }}>
        Key Points:
      </Typography>
      <Box component="ul" sx={{ m: 0, pl: 3 }}>
        {content.keypoints.map((point, idx) => (
          <li key={idx}>
            <Typography variant="body2">{point}</Typography>
          </li>
        ))}
      </Box>

      <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 2 }}>
        Generated by {content.ai_model} on {new Date(content.generated_at).toLocaleDateString()}
      </Typography>
    </Box>
  );
};
