"""Reading context schemas."""

from src.infrastructure.common.schemas.position_schemas import PositionResponse
from src.infrastructure.reading.schemas.bookmark_schemas import (
    Bookmark,
    BookmarkBase,
    BookmarkCreateRequest,
    BookmarksResponse,
)
from src.infrastructure.reading.schemas.highlight_schemas import (
    BookDetails,
    BookHighlightSearchResponse,
    ChapterWithHighlights,
    Highlight,
    HighlightBase,
    HighlightCreate,
    HighlightDeleteRequest,
    HighlightDeleteResponse,
    HighlightLabel,
    HighlightLabelCreate,
    HighlightLabelInBook,
    HighlightLabelUpdate,
    HighlightNoteUpdate,
    HighlightNoteUpdateResponse,
    HighlightResponseBase,
    HighlightUploadRequest,
    HighlightUploadResponse,
)
from src.infrastructure.reading.schemas.highlight_tag_schemas import (
    HighlightTag,
    HighlightTagAssociationRequest,
    HighlightTagCreateRequest,
    HighlightTagGroup,
    HighlightTagGroupCreateRequest,
    HighlightTagGroupInBook,
    HighlightTagInBook,
    HighlightTagsResponse,
    HighlightTagUpdateRequest,
)
from src.infrastructure.reading.schemas.reading_session_schemas import (
    ReadingSession,
    ReadingSessionAISummaryResponse,
    ReadingSessionsResponse,
    ReadingSessionUploadRequest,
    ReadingSessionUploadResponse,
    ReadingSessionUploadSessionItem,
)

__all__ = [
    "BookDetails",
    "BookHighlightSearchResponse",
    "Bookmark",
    "BookmarkBase",
    "BookmarkCreateRequest",
    "BookmarksResponse",
    "ChapterWithHighlights",
    "Highlight",
    "HighlightBase",
    "HighlightCreate",
    "HighlightDeleteRequest",
    "HighlightDeleteResponse",
    "HighlightLabel",
    "HighlightLabelCreate",
    "HighlightLabelInBook",
    "HighlightLabelUpdate",
    "HighlightNoteUpdate",
    "HighlightNoteUpdateResponse",
    "HighlightResponseBase",
    "HighlightTag",
    "HighlightTagAssociationRequest",
    "HighlightTagCreateRequest",
    "HighlightTagGroup",
    "HighlightTagGroupCreateRequest",
    "HighlightTagGroupInBook",
    "HighlightTagInBook",
    "HighlightTagUpdateRequest",
    "HighlightTagsResponse",
    "HighlightUploadRequest",
    "HighlightUploadResponse",
    "PositionResponse",
    "ReadingSession",
    "ReadingSessionAISummaryResponse",
    "ReadingSessionUploadRequest",
    "ReadingSessionUploadResponse",
    "ReadingSessionUploadSessionItem",
    "ReadingSessionsResponse",
]
