"""Reading context schemas."""

from src.infrastructure.common.schemas.position_schemas import PositionResponse
from src.infrastructure.reading.schemas.bookmark_schemas import (
    Bookmark,
    BookmarkBase,
    BookmarkCreateRequest,
    BookmarksResponse,
)
from src.infrastructure.reading.schemas.highlight_schemas import (
    BookDetails,
    BookHighlightSearchResponse,
    ChapterWithHighlights,
    Highlight,
    HighlightBase,
    HighlightCreate,
    HighlightDeleteRequest,
    HighlightDeleteResponse,
    HighlightLabel,
    HighlightLabelCreate,
    HighlightLabelInBook,
    HighlightLabelUpdate,
    HighlightNoteUpdate,
    HighlightNoteUpdateResponse,
    HighlightResponseBase,
    HighlightUploadRequest,
    HighlightUploadResponse,
)
from src.infrastructure.reading.schemas.reading_session_schemas import (
    ReadingSession,
    ReadingSessionAISummaryResponse,
    ReadingSessionsResponse,
    ReadingSessionUploadRequest,
    ReadingSessionUploadResponse,
    ReadingSessionUploadSessionItem,
)
from src.infrastructure.reading.schemas.tag_schemas import (
    Tag,
    TagAssociationRequest,
    TagCreateRequest,
    TagGroup,
    TagGroupCreateRequest,
    TagGroupInBook,
    TagInBook,
    TagsResponse,
    TagUpdateRequest,
)

__all__ = [
    "BookDetails",
    "BookHighlightSearchResponse",
    "Bookmark",
    "BookmarkBase",
    "BookmarkCreateRequest",
    "BookmarksResponse",
    "ChapterWithHighlights",
    "Highlight",
    "HighlightBase",
    "HighlightCreate",
    "HighlightDeleteRequest",
    "HighlightDeleteResponse",
    "HighlightLabel",
    "HighlightLabelCreate",
    "HighlightLabelInBook",
    "HighlightLabelUpdate",
    "HighlightNoteUpdate",
    "HighlightNoteUpdateResponse",
    "HighlightResponseBase",
    "HighlightUploadRequest",
    "HighlightUploadResponse",
    "PositionResponse",
    "ReadingSession",
    "ReadingSessionAISummaryResponse",
    "ReadingSessionUploadRequest",
    "ReadingSessionUploadResponse",
    "ReadingSessionUploadSessionItem",
    "ReadingSessionsResponse",
    "Tag",
    "TagAssociationRequest",
    "TagCreateRequest",
    "TagGroup",
    "TagGroupCreateRequest",
    "TagGroupInBook",
    "TagInBook",
    "TagUpdateRequest",
    "TagsResponse",
]
