from typing import Protocol

from src.domain.batch.entities.batch_item import BatchItem
from src.domain.batch.entities.batch_job import BatchJob
from src.domain.common.value_objects.ids import BatchJobId, BookId, UserId


class BatchJobRepositoryProtocol(Protocol):
    async def save_job(self, job: BatchJob) -> BatchJob: ...
    async def save_item(self, item: BatchItem) -> BatchItem: ...
    async def save_items(self, items: list[BatchItem]) -> list[BatchItem]: ...
    async def get_job(self, job_id: BatchJobId) -> BatchJob | None: ...
    async def get_job_items(self, job_id: BatchJobId) -> list[BatchItem]: ...
    async def get_pending_items(self, job_id: BatchJobId) -> list[BatchItem]: ...
    async def find_active_job(
        self, user_id: UserId, book_id: BookId, job_type: str
    ) -> BatchJob | None: ...
