from typing import Protocol


class PasswordServiceProtocol(Protocol):
    def hash_password(self, plain_password: str) -> str: ...

    def verify_password(self, plain_password: str, hashed_password: str) -> bool: ...

    def get_dummy_hash(self) -> str: ...
