from typing import Protocol

from src.domain.common.value_objects.ids import BookId, ChapterId, PrereadingContentId
from src.domain.reading.entities.chapter_prereading_content import ChapterPrereadingContent


class ChapterPrereadingRepositoryProtocol(Protocol):
    async def find_by_id(self, id: PrereadingContentId) -> ChapterPrereadingContent | None: ...
    async def find_by_chapter_id(
        self, chapter_id: ChapterId
    ) -> ChapterPrereadingContent | None: ...
    async def find_all_by_book_id(self, book_id: BookId) -> list[ChapterPrereadingContent]: ...
    async def save(self, content: ChapterPrereadingContent) -> ChapterPrereadingContent: ...
    async def delete(self, id: PrereadingContentId) -> None: ...
