from typing import Protocol

from src.domain.common.value_objects.ids import BookId, ChapterId, PrereadingContentId
from src.domain.reading.entities.chapter_prereading_content import ChapterPrereadingContent


class ChapterPrereadingRepositoryProtocol(Protocol):
    def find_by_id(self, id: PrereadingContentId) -> ChapterPrereadingContent | None: ...
    def find_by_chapter_id(self, chapter_id: ChapterId) -> ChapterPrereadingContent | None: ...
    def find_all_by_book_id(self, book_id: BookId) -> list[ChapterPrereadingContent]: ...
    def save(self, content: ChapterPrereadingContent) -> ChapterPrereadingContent: ...
    def delete(self, id: PrereadingContentId) -> None: ...
